
Create DATABASE db_shop;
USE db_shop;

DROP TABLE IF EXISTS tb_user;
CREATE TABLE tb_user (
  id INT NOT NULL AUTO_INCREMENT,
  login_name VARCHAR(100) NOT NULL,
  password VARBINARY(128) DEFAULT NULL,
  nickname VARCHAR(50) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  last_login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  register_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY (login_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
